### ISSUE TITLE
Week 13 HW Feedback

### ISSUE THREAD

**Issue by albertbahia** [stvbuller/Portfolio#1]
@stvbuller Nice job with the routes!  For https://github.com/stvbuller/Portfolio/blob/master/server.js#L20-L25, you can DRY it up even further, perhaps having just one folder for images and another for your scripts.  This would be a great time to experiment with that.

**Comment by stbuller** [comment]
moved the click game images into the images folder and the click game jscripts into the jscripts folder and tested, it works
